git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/dao/ResultInfo.java
git add src/main/webapp/static/images/BLAST.png
git add src/main/webapp/static/images/BLAT.png
git add src/main/webapp/static/images/jbrowse.png
git add src/main/webapp/static/images/text-search.png
git add target/classes/application.properties
git add target/classes/jp/ac/nig/ddbj/webapp/dstextsearch/Application.class
git add target/classes/jp/ac/nig/ddbj/webapp/dstextsearch/ConfigurationForTiles.class
git add target/classes/jp/ac/nig/ddbj/webapp/dstextsearch/controller/MainController.class
git add target/classes/jp/ac/nig/ddbj/webapp/dstextsearch/dao/ResultInfo.class
git add target/ds-text-search-0.2.0.jar
git add target/ds-text-search-0.2.0.jar.original
git add target/maven-archiver/pom.properties
git add target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
git add target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
git add target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
git add target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
git add target/surefire-reports/TEST-jp.ac.nig.ddbj.webapp.dstextsearch.ApplicationTests.xml
git add target/surefire-reports/jp.ac.nig.ddbj.webapp.dstextsearch.ApplicationTests.txt
git add target/test-classes/jp/ac/nig/ddbj/webapp/dstextsearch/ApplicationTests.class
git add target/test-classes/jp/ac/nig/ddbj/webapp/dstextsearch/TestConfigurtaion.class
git add git_add.sh
git add pom.xml
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/Application.java
git add src/main/java/jp/ac/nig/ddbj/webapp/dstextsearch/controller/MainController.java
git add src/main/resources/application.properties
git add src/main/webapp/WEB-INF/tiles/layout/basic.jsp
git add src/main/webapp/WEB-INF/tiles/view/body/body.jsp
git add src/main/webapp/WEB-INF/tiles/view/footer.jsp
git add src/main/webapp/WEB-INF/tiles/view/header.jsp
